# Generated by Django 4.2.7 on 2025-09-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du type de congé (ex: Congés payés, Maladie)', max_length=100, unique=True, verbose_name='Nom du type')),
                ('description', models.TextField(blank=True, help_text='Description du type de congé', null=True, verbose_name='Description')),
                ('code', models.CharField(help_text='Code court pour identifier le type (ex: CP, MAL)', max_length=10, unique=True, verbose_name='Code')),
                ('unit', models.CharField(choices=[('days', 'Jours'), ('hours', 'Heures')], default='days', help_text='Unité de calcul (jours ou heures)', max_length=10, verbose_name='Unité')),
                ('allocation_type', models.CharField(choices=[('annual', 'Annuelle'), ('monthly', 'Mensuelle'), ('on_demand', 'Sur demande')], default='annual', help_text='Comment les congés sont attribués', max_length=20, verbose_name="Type d'attribution")),
                ('allocation_amount', models.DecimalField(decimal_places=2, default=0, help_text='Quantité attribuée (ex: 25 jours par an)', max_digits=5, verbose_name="Montant d'attribution")),
                ('max_consecutive_days', models.PositiveIntegerField(default=30, help_text='Nombre maximum de jours consécutifs autorisés', verbose_name='Maximum consécutif')),
                ('requires_justification', models.BooleanField(default=False, help_text='Une justification est-elle requise ?', verbose_name='Justification requise')),
                ('requires_medical_certificate', models.BooleanField(default=False, help_text='Un certificat médical est-il requis ?', verbose_name='Certificat médical')),
                ('advance_notice_days', models.PositiveIntegerField(default=0, help_text="Nombre de jours d'avance requis", verbose_name='Préavis (jours)')),
                ('is_paid', models.BooleanField(default=True, help_text='Le congé est-il rémunéré ?', verbose_name='Rémunéré')),
                ('is_active', models.BooleanField(default=True, help_text='Type de congé disponible', verbose_name='Actif')),
                ('color', models.CharField(default='#007bff', help_text="Couleur hexadécimale pour l'affichage", max_length=7, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congés',
                'ordering': ['name'],
            },
        ),
    ]
