# Generated by Django 4.2.7 on 2025-09-29 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date de début du congé', verbose_name='Date de début')),
                ('end_date', models.DateField(help_text='Date de fin du congé', verbose_name='Date de fin')),
                ('duration_days', models.DecimalField(decimal_places=2, help_text='Durée du congé en jours', max_digits=5, verbose_name='Durée (jours)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved_manager', 'Approuvé par Manager'), ('approved_rh', 'Approuvé par RH'), ('rejected_manager', 'Rejeté par Manager'), ('rejected_rh', 'Rejeté par RH'), ('cancelled', 'Annulé')], default='pending', help_text='Statut actuel de la demande', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', help_text='Priorité de la demande', max_length=10, verbose_name='Priorité')),
                ('reason', models.TextField(help_text='Motif de la demande de congé', verbose_name='Motif')),
                ('justification', models.TextField(blank=True, help_text='Justification détaillée si nécessaire', null=True, verbose_name='Justification')),
                ('medical_certificate', models.FileField(blank=True, help_text='Certificat médical si requis', null=True, upload_to='medical_certificates/', verbose_name='Certificat médical')),
                ('manager_decision', models.CharField(blank=True, choices=[('pending', 'En attente'), ('approved_manager', 'Approuvé par Manager'), ('approved_rh', 'Approuvé par RH'), ('rejected_manager', 'Rejeté par Manager'), ('rejected_rh', 'Rejeté par RH'), ('cancelled', 'Annulé')], help_text='Décision du manager', max_length=20, null=True, verbose_name='Décision Manager')),
                ('manager_comment', models.TextField(blank=True, help_text='Commentaire du manager', null=True, verbose_name='Commentaire Manager')),
                ('manager_decision_at', models.DateTimeField(blank=True, help_text='Date de décision du manager', null=True, verbose_name='Décision Manager le')),
                ('rh_decision', models.CharField(blank=True, choices=[('pending', 'En attente'), ('approved_manager', 'Approuvé par Manager'), ('approved_rh', 'Approuvé par RH'), ('rejected_manager', 'Rejeté par Manager'), ('rejected_rh', 'Rejeté par RH'), ('cancelled', 'Annulé')], help_text='Décision du RH/DG', max_length=20, null=True, verbose_name='Décision RH')),
                ('rh_comment', models.TextField(blank=True, help_text='Commentaire du RH/DG', null=True, verbose_name='Commentaire RH')),
                ('rh_decision_at', models.DateTimeField(blank=True, help_text='Date de décision du RH/DG', null=True, verbose_name='Décision RH le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('employee', models.ForeignKey(help_text='Employé qui fait la demande', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
                ('leave_type', models.ForeignKey(help_text='Type de congé demandé', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='leave.leavetype', verbose_name='Type de congé')),
                ('manager', models.ForeignKey(blank=True, help_text='Manager responsable de la validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2024, help_text='Année de référence', verbose_name='Année')),
                ('allocated_balance', models.DecimalField(decimal_places=2, default=0, help_text="Congés alloués pour l'année", max_digits=5, verbose_name='Solde alloué')),
                ('taken_balance', models.DecimalField(decimal_places=2, default=0, help_text="Congés pris pendant l'année", max_digits=5, verbose_name='Solde pris')),
                ('carried_over_balance', models.DecimalField(decimal_places=2, default=0, help_text="Congés reportés de l'année précédente", max_digits=5, verbose_name='Solde reporté')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('employee', models.ForeignKey(help_text='Employé concerné', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
                ('leave_type', models.ForeignKey(help_text='Type de congé', on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave.leavetype', verbose_name='Type de congé')),
            ],
            options={
                'verbose_name': 'Solde de congé',
                'verbose_name_plural': 'Soldes de congés',
                'ordering': ['employee', 'leave_type', '-year'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
