# Generated by Django 4.2.7 on 2025-09-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaverequest_leavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du jour férié', max_length=100, verbose_name='Nom')),
                ('date', models.DateField(help_text='Date du jour férié', verbose_name='Date')),
                ('holiday_type', models.CharField(choices=[('national', 'Férié national'), ('regional', 'Férié régional'), ('company', "Jour de l'entreprise"), ('religious', 'Fête religieuse')], default='national', help_text='Type de jour férié', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, help_text='Description du jour férié', null=True, verbose_name='Description')),
                ('is_recurring', models.BooleanField(default=False, help_text='Ce jour férié se répète chaque année', verbose_name='Récurrent')),
                ('is_active', models.BooleanField(default=True, help_text='Jour férié actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'ordering': ['date'],
            },
        ),
    ]
