# Generated by Django 5.2.7 on 2025-10-25 09:28

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='justification',
            field=models.TextField(blank=True, help_text='Justification détaillée si nécessaire', null=True, validators=[common.validators.validate_reason_text], verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(help_text='Motif de la demande de congé', validators=[common.validators.validate_reason_text], verbose_name='Motif'),
        ),
    ]
