# Generated by Django 5.2.7 on 2025-10-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leaverequest_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='deducts_balance',
            field=models.BooleanField(default=True, help_text='Ce type de congé déduit-il du solde annuel ? (Faux pour congés exceptionnels/maladie)', verbose_name='Déduit du solde'),
        ),
    ]
