# Generated by Django 5.2.7 on 2025-11-03 09:15

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_drop_priority_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='medical_certificate',
        ),
        # Note: priority a déjà été supprimé dans la migration 0006, donc pas besoin de le supprimer ici
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Motif de la demande de congé (optionnel pour les congés payés, obligatoire pour les autres types)', null=True, validators=[common.validators.validate_reason_text], verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rh_comment',
            field=models.TextField(blank=True, help_text='Commentaire du RH', null=True, verbose_name='Commentaire RH'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rh_decision',
            field=models.CharField(blank=True, choices=[('pending', 'En attente'), ('approved_manager', 'Approuvé par Manager'), ('approved_rh', 'Approuvé par RH'), ('rejected_manager', 'Rejeté par Manager'), ('rejected_rh', 'Rejeté par RH'), ('cancelled', 'Annulé')], help_text='Décision du RH', max_length=20, null=True, verbose_name='Décision RH'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rh_decision_at',
            field=models.DateTimeField(blank=True, help_text='Date de décision du RH', null=True, verbose_name='Décision RH le'),
        ),
    ]
