# Generated by Django 5.2.7 on 2025-11-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_remove_leaverequest_medical_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='priority',
        ),
    ]
