# Generated by Django 5.2.7 on 2025-11-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_remove_leaverequest_medical_certificate_and_more'),
    ]

    operations = [
        # Note: La colonne priority a déjà été supprimée par la migration 0006 (RunSQL)
        # Cette migration utilise SeparateDatabaseAndState pour mettre à jour l'état Django
        # sans tenter de supprimer la colonne qui n'existe plus
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Ne rien faire en base (colonne déjà supprimée par migration 0006)
                # Utiliser RunSQL avec une requête qui ne fait rien mais qui est valide
                migrations.RunSQL(
                    sql="SELECT 1;",  # Requête SQL valide qui ne fait rien
                    reverse_sql="SELECT 1;",
                ),
            ],
            state_operations=[
                # Mettre à jour l'état Django pour refléter que le champ est supprimé
                migrations.RemoveField(
                    model_name='leaverequest',
                    name='priority',
                ),
            ],
        ),
    ]
