# Generated by Django 4.2.7 on 2025-09-29 22:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du département (ex: IT, RH, Ventes)', max_length=100, unique=True, verbose_name='Nom du département')),
                ('description', models.TextField(blank=True, help_text='Description du département et de ses responsabilités', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Département actif ou fermé', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('manager', models.ForeignKey(blank=True, help_text='Manager responsable de ce département', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text="Identifiant unique de l'employé (ex: EMP001)", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="L'ID employé doit contenir uniquement des lettres majuscules et des chiffres", regex='^[A-Z0-9]+$')], verbose_name='ID Employé')),
                ('role', models.CharField(choices=[('employee', 'Employé'), ('manager', 'Manager'), ('rh_dg', 'RH/DG'), ('admin', 'Administrateur')], default='employee', help_text="Rôle de l'employé dans le système", max_length=20, verbose_name='Rôle')),
                ('employee_type', models.CharField(choices=[('monthly', 'Mensuel'), ('daily', 'Journalier'), ('intern', 'Stagiaire')], default='monthly', help_text="Type de contrat de l'employé", max_length=20, verbose_name="Type d'employé")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu')], default='active', help_text="Statut de l'employé", max_length=20, verbose_name='Statut')),
                ('phone', models.CharField(blank=True, help_text="Numéro de téléphone de l'employé", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide', regex='^\\+?[0-9\\s\\-\\(\\)]+$')], verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, help_text="Adresse de l'employé", null=True, verbose_name='Adresse')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, help_text="Date d'embauche de l'employé", verbose_name="Date d'embauche")),
                ('contract_end_date', models.DateField(blank=True, help_text='Date de fin de contrat (si applicable)', null=True, verbose_name='Fin de contrat')),
                ('is_active', models.BooleanField(default=True, help_text='Employé actif dans le système', verbose_name='Actif')),
                ('can_punch', models.BooleanField(default=True, help_text="L'employé peut-il pointer (false pour DG/Admin)", verbose_name='Peut pointer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('department', models.ForeignKey(blank=True, help_text="Département auquel appartient l'employé", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.department', verbose_name='Département')),
                ('manager', models.ForeignKey(blank=True, help_text='Manager direct de cet employé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('user', models.OneToOneField(help_text='Compte utilisateur Django associé', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Employé',
                'verbose_name_plural': 'Profils Employés',
                'ordering': ['employee_id'],
            },
        ),
    ]
