# Generated by Django 5.2.6 on 2025-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text="L'employé doit changer son mot de passe à la prochaine connexion", verbose_name='Changement de mot de passe requis'),
        ),
    ]
