# Generated by Django 5.2.7 on 2025-10-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employeeprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='position',
            field=models.CharField(blank=True, help_text="Poste ou fonction de l'employé", max_length=100, null=True, verbose_name='Poste'),
        ),
    ]
