# Generated by Django 5.2.7 on 2025-10-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeeprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='status',
        ),
    ]
