# Generated by Django 5.2.7 on 2025-10-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_employeeprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employé'), ('manager', 'Manager'), ('rh_dg', 'RH/DG')], default='employee', help_text="Rôle de l'employé dans le système", max_length=20, verbose_name='Rôle'),
        ),
    ]
