# Generated by Django 5.2.7 on 2025-10-27 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_employeeprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Bureau Standard, Mi-temps, Équipe Matin', max_length=100, unique=True, verbose_name='Nom du profil')),
                ('description', models.TextField(blank=True, help_text="Description du profil horaire et à qui il s'applique", null=True, verbose_name='Description')),
                ('start_time', models.TimeField(help_text='Heure de début contractuelle (ex: 8h00)', verbose_name='Heure début contrat (HDC)')),
                ('end_time', models.TimeField(help_text='Heure de fin contractuelle (ex: 18h00)', verbose_name='Heure fin contrat (HFC)')),
                ('pause_start', models.TimeField(help_text='Heure de début de la pause (ex: 12h00)', verbose_name='Début de pause')),
                ('pause_end', models.TimeField(help_text='Heure de fin de la pause (ex: 14h00)', verbose_name='Fin de pause')),
                ('is_default', models.BooleanField(default=False, help_text='Utilisé pour les nouveaux employés si aucun profil spécifié', verbose_name='Profil par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur (RH) qui a créé ce profil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Profil Horaire',
                'verbose_name_plural': 'Profils Horaires',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='current_work_schedule',
            field=models.ForeignKey(blank=True, help_text='Profil horaire actuellement appliqué à cet employé', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.workschedule', verbose_name='Profil horaire actuel'),
        ),
        migrations.CreateModel(
            name='EmployeeScheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(help_text="Date à partir de laquelle ce profil est actif pour l'employé", verbose_name="Date d'affectation")),
                ('end_date', models.DateField(blank=True, help_text="NULL si c'est le profil actif, sinon date de fin d'utilisation", null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('assigned_by', models.ForeignKey(help_text="Utilisateur (RH) qui a fait l'affectation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_history', to='accounts.employeeprofile', verbose_name='Employé')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='accounts.workschedule', verbose_name='Profil horaire')),
            ],
            options={
                'verbose_name': 'Historique Profil Horaire',
                'verbose_name_plural': 'Historiques Profils Horaires',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['employee', 'assigned_date', 'end_date'], name='accounts_em_employe_8795c4_idx')],
            },
        ),
    ]
