# Generated by Django 5.2.7 on 2025-11-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_workschedule_employeeprofile_current_work_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employé'), ('manager', 'Manager'), ('rh', 'RH')], default='employee', help_text="Rôle de l'employé dans le système", max_length=20, verbose_name='Rôle'),
        ),
    ]
