# Generated by Django 4.2.7 on 2025-09-29 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Clé unique du paramètre', max_length=100, unique=True, verbose_name='Clé')),
                ('value', models.TextField(help_text='Valeur du paramètre', verbose_name='Valeur')),
                ('setting_type', models.CharField(choices=[('general', 'Général'), ('attendance', 'Pointage'), ('leave', 'Congés'), ('notification', 'Notifications'), ('security', 'Sécurité')], default='general', help_text='Type de paramètre', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, help_text='Description du paramètre', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Paramètre actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a modifié le paramètre', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
                'ordering': ['setting_type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du modèle de rapport', max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description du modèle de rapport', null=True, verbose_name='Description')),
                ('report_type', models.CharField(choices=[('attendance', 'Rapport de présence'), ('leave', 'Rapport de congés'), ('anomaly', "Rapport d'anomalies"), ('summary', 'Rapport récapitulatif'), ('custom', 'Rapport personnalisé')], help_text='Type de rapport', max_length=20, verbose_name='Type de rapport')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', help_text='Format de sortie du rapport', max_length=10, verbose_name='Format')),
                ('template_content', models.TextField(help_text='Contenu du modèle de rapport (template)', verbose_name='Contenu du modèle')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Paramètres du rapport au format JSON', verbose_name='Paramètres')),
                ('is_active', models.BooleanField(default=True, help_text='Modèle de rapport actif', verbose_name='Actif')),
                ('is_public', models.BooleanField(default=False, help_text='Modèle accessible à tous les utilisateurs', verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé le modèle', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Modèle de rapport',
                'verbose_name_plural': 'Modèles de rapports',
                'ordering': ['report_type', 'name'],
            },
        ),
    ]
