# Generated by Django 5.2.6 on 2025-10-06 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom descriptif du template', max_length=100, verbose_name='Nom du template')),
                ('template_type', models.CharField(choices=[('leave_request_created', 'Demande de congé créée'), ('leave_request_approved_manager', 'Congé approuvé par manager'), ('leave_request_rejected_manager', 'Congé rejeté par manager'), ('leave_request_approved_rh', 'Congé approuvé par RH/DG'), ('leave_request_rejected_rh', 'Congé rejeté par RH/DG'), ('leave_reminder', 'Rappel de congé'), ('attendance_anomaly', 'Anomalie de présence'), ('password_reset', 'Réinitialisation de mot de passe'), ('welcome', 'Message de bienvenue')], help_text='Type de notification', max_length=50, unique=True, verbose_name='Type de template')),
                ('subject', models.CharField(help_text="Sujet de l'email", max_length=200, verbose_name='Sujet')),
                ('html_content', models.TextField(help_text="Contenu HTML de l'email", verbose_name='Contenu HTML')),
                ('text_content', models.TextField(blank=True, help_text='Contenu texte alternatif', verbose_name='Contenu texte')),
                ('is_active', models.BooleanField(default=True, help_text='Template disponible', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Template d'email",
                'verbose_name_plural': "Templates d'emails",
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Recevoir les notifications par email', verbose_name='Notifications par email')),
                ('email_frequency', models.CharField(choices=[('immediate', 'Immédiat'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire')], default='immediate', help_text="Fréquence d'envoi des emails", max_length=20, verbose_name='Fréquence des emails')),
                ('leave_notifications', models.BooleanField(default=True, help_text='Notifications liées aux congés', verbose_name='Notifications de congés')),
                ('attendance_notifications', models.BooleanField(default=True, help_text='Notifications liées à la présence', verbose_name='Notifications de présence')),
                ('system_notifications', models.BooleanField(default=True, help_text='Notifications système importantes', verbose_name='Notifications système')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Heure de début des heures silencieuses', null=True, verbose_name='Début heures silencieuses')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Heure de fin des heures silencieuses', null=True, verbose_name='Fin heures silencieuses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paramètres de notifications',
                'verbose_name_plural': 'Paramètres de notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre de la notification', max_length=200, verbose_name='Titre')),
                ('message', models.TextField(help_text='Contenu de la notification', verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', help_text='Type de notification', max_length=20, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='normal', help_text='Niveau de priorité', max_length=10, verbose_name='Priorité')),
                ('is_read', models.BooleanField(default=False, help_text='Notification lue', verbose_name='Lu')),
                ('is_sent', models.BooleanField(default=False, help_text='Email envoyé', verbose_name='Envoyé')),
                ('action_url', models.URLField(blank=True, help_text="Lien vers l'action à effectuer", null=True, verbose_name="URL d'action")),
                ('action_text', models.CharField(blank=True, help_text="Texte du bouton d'action", max_length=100, verbose_name="Texte d'action")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('user', models.ForeignKey(help_text='Utilisateur destinataire', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx')],
            },
        ),
    ]
