# Generated by Django 4.2.7 on 2025-09-29 22:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date du pointage', verbose_name='Date')),
                ('punch_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], help_text='Entrée ou sortie', max_length=10, verbose_name='Type de pointage')),
                ('time', models.TimeField(help_text='Heure du pointage', verbose_name='Heure')),
                ('latitude', models.FloatField(help_text='Latitude GPS du pointage', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='Longitude GPS du pointage', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('accuracy', models.FloatField(help_text='Précision GPS en mètres', verbose_name='Précision GPS')),
                ('distance_from_site', models.FloatField(blank=True, help_text='Distance calculée du centre du site en mètres', null=True, verbose_name='Distance du site')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('late', 'En retard'), ('early', 'Sortie anticipée'), ('missing_out', 'Sortie oubliée'), ('double_punch', 'Double pointage'), ('outside_zone', 'Hors zone'), ('low_accuracy', 'Précision faible')], default='normal', help_text='Statut du pointage (normal, retard, etc.)', max_length=20, verbose_name='Statut')),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('kiosk', 'Kiosque'), ('admin', 'Administration')], default='web', help_text='Source du pointage', max_length=10, verbose_name='Source')),
                ('user_agent', models.TextField(blank=True, help_text='Navigateur/appareil utilisé pour le pointage', null=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'appareil", null=True, verbose_name='Adresse IP')),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires sur le pointage', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('employee', models.ForeignKey(help_text='Employé qui effectue le pointage', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date', '-time'],
                'unique_together': {('employee', 'date', 'punch_type')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('late_arrival', 'Arrivée en retard'), ('early_departure', 'Départ anticipé'), ('missing_punch_out', 'Oubli de sortie'), ('outside_zone', 'Pointage hors zone'), ('low_accuracy', 'Précision GPS faible'), ('double_punch', 'Double pointage'), ('long_duration', 'Durée de travail excessive')], help_text="Type d'anomalie détectée", max_length=20, verbose_name="Type d'anomalie")),
                ('description', models.TextField(help_text="Description détaillée de l'anomalie", verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('justified', 'Justifiée'), ('resolved', 'Résolue'), ('ignored', 'Ignorée')], default='pending', help_text="Statut de résolution de l'anomalie", max_length=20, verbose_name='Statut')),
                ('justification', models.TextField(blank=True, help_text="Justification fournie par l'employé ou le manager", null=True, verbose_name='Justification')),
                ('resolved_at', models.DateTimeField(blank=True, help_text="Date de résolution de l'anomalie", null=True, verbose_name='Résolu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('attendance', models.ForeignKey(help_text="Pointage concerné par l'anomalie", on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='attendance.attendance', verbose_name='Pointage')),
                ('resolved_by', models.ForeignKey(blank=True, help_text="Manager qui a résolu l'anomalie", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
            ],
            options={
                'verbose_name': 'Anomalie de pointage',
                'verbose_name_plural': 'Anomalies de pointage',
                'ordering': ['-created_at'],
            },
        ),
    ]
