# Generated by Django 5.2.6 on 2025-10-06 21:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom descriptif de la règle', max_length=100, unique=True, verbose_name='Nom de la configuration')),
                ('config_type', models.CharField(choices=[('daily', 'Heures quotidiennes'), ('weekly', 'Heures hebdomadaires'), ('weekend', 'Weekend'), ('holiday', 'Jours fériés'), ('night', 'Heures de nuit')], help_text="Type de règle d'heures supplémentaires", max_length=20, verbose_name='Type de configuration')),
                ('daily_hours_limit', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text="Nombre d'heures par jour avant déclenchement des heures supplémentaires", max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Limite d'heures quotidiennes")),
                ('weekly_hours_limit', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text="Nombre d'heures par semaine avant déclenchement des heures supplémentaires", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Limite d'heures hebdomadaires")),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Multiplicateur du salaire horaire (ex: 1.5 = 50% de majoration)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Multiplicateur heures supplémentaires')),
                ('night_start_hour', models.TimeField(blank=True, help_text='Heure de début des heures de nuit (ex: 22:00)', null=True, verbose_name='Début des heures de nuit')),
                ('night_end_hour', models.TimeField(blank=True, help_text='Heure de fin des heures de nuit (ex: 06:00)', null=True, verbose_name='Fin des heures de nuit')),
                ('is_active', models.BooleanField(default=True, help_text='Cette configuration est-elle active ?', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Configuration heures supplémentaires',
                'verbose_name_plural': 'Configurations heures supplémentaires',
                'ordering': ['config_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_type', models.CharField(choices=[('planned', 'Planifiées'), ('unplanned', 'Non planifiées'), ('emergency', 'Urgentes'), ('project', 'Projet')], default='unplanned', help_text="Type de demande d'heures supplémentaires", max_length=20, verbose_name="Type d'heures supplémentaires")),
                ('date', models.DateField(help_text='Date des heures supplémentaires', verbose_name='Date')),
                ('start_time', models.TimeField(help_text='Heure de début des heures supplémentaires', verbose_name='Heure de début')),
                ('end_time', models.TimeField(help_text='Heure de fin des heures supplémentaires', verbose_name='Heure de fin')),
                ('hours_requested', models.DecimalField(decimal_places=2, help_text="Nombre d'heures supplémentaires demandées", max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Heures demandées')),
                ('reason', models.TextField(help_text="Motif de la demande d'heures supplémentaires", verbose_name='Motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvées'), ('rejected', 'Rejetées'), ('cancelled', 'Annulées')], default='pending', help_text='Statut de la demande', max_length=20, verbose_name='Statut')),
                ('manager_decision', models.CharField(blank=True, choices=[('pending', 'En attente'), ('approved', 'Approuvées'), ('rejected', 'Rejetées'), ('cancelled', 'Annulées')], help_text='Décision du manager', max_length=20, null=True, verbose_name='Décision Manager')),
                ('manager_comment', models.TextField(blank=True, help_text='Commentaire du manager', null=True, verbose_name='Commentaire Manager')),
                ('manager_decision_at', models.DateTimeField(blank=True, help_text='Date de décision du manager', null=True, verbose_name='Décision Manager le')),
                ('rh_decision', models.CharField(blank=True, choices=[('pending', 'En attente'), ('approved', 'Approuvées'), ('rejected', 'Rejetées'), ('cancelled', 'Annulées')], help_text='Décision du RH/DG', max_length=20, null=True, verbose_name='Décision RH')),
                ('rh_comment', models.TextField(blank=True, help_text='Commentaire du RH/DG', null=True, verbose_name='Commentaire RH')),
                ('rh_decision_at', models.DateTimeField(blank=True, help_text='Date de décision du RH/DG', null=True, verbose_name='Décision RH le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('employee', models.ForeignKey(help_text='Employé qui demande les heures supplémentaires', on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
                ('manager', models.ForeignKey(blank=True, help_text='Manager responsable de la validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': "Demande d'heures supplémentaires",
                'verbose_name_plural': "Demandes d'heures supplémentaires",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date du calcul', verbose_name='Date')),
                ('total_hours_worked', models.DecimalField(decimal_places=2, help_text="Nombre total d'heures travaillées dans la journée", max_digits=5, verbose_name='Heures totales travaillées')),
                ('normal_hours', models.DecimalField(decimal_places=2, help_text="Nombre d'heures normales", max_digits=4, verbose_name='Heures normales')),
                ('overtime_hours', models.DecimalField(decimal_places=2, help_text="Nombre d'heures supplémentaires", max_digits=4, verbose_name='Heures supplémentaires')),
                ('daily_overtime', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Heures supplémentaires au-delà de la limite quotidienne', max_digits=4, verbose_name='Heures supplémentaires quotidiennes')),
                ('weekend_overtime', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Heures supplémentaires travaillées le weekend', max_digits=4, verbose_name='Heures supplémentaires weekend')),
                ('holiday_overtime', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Heures supplémentaires travaillées les jours fériés', max_digits=4, verbose_name='Heures supplémentaires jours fériés')),
                ('night_overtime', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Heures supplémentaires travaillées la nuit', max_digits=4, verbose_name='Heures supplémentaires nuit')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant calculé des heures supplémentaires', max_digits=8, verbose_name='Montant heures supplémentaires')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text="Taux horaire de l'employé", max_digits=6, verbose_name='Taux horaire')),
                ('is_approved', models.BooleanField(default=False, help_text='Le calcul a-t-il été approuvé par le manager ?', verbose_name='Approuvé')),
                ('approved_at', models.DateTimeField(blank=True, help_text="Date d'approbation", null=True, verbose_name='Approuvé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager qui a approuvé le calcul', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime_calculations', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('employee', models.ForeignKey(help_text='Employé concerné par le calcul', on_delete=django.db.models.deletion.CASCADE, related_name='overtime_calculations', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Calcul heures supplémentaires',
                'verbose_name_plural': 'Calculs heures supplémentaires',
                'ordering': ['-date', '-employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
