# Generated by Django 5.2.6 on 2025-10-06 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_overtimeconfiguration_overtimerequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimeconfiguration',
            name='overtime_multiplier',
        ),
        migrations.DeleteModel(
            name='OvertimeCalculation',
        ),
    ]
