# Generated by Django 5.2.6 on 2025-10-06 23:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_overtimeconfiguration_overtime_multiplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimeconfiguration',
            options={'ordering': ['config_type', 'name'], 'verbose_name': 'Configuration Heures Supplémentaires', 'verbose_name_plural': 'Configurations Heures Supplémentaires'},
        ),
        migrations.AlterField(
            model_name='overtimeconfiguration',
            name='night_end_hour',
            field=models.TimeField(blank=True, help_text='Heure de fin des heures de nuit (ex: 06:00)', null=True, verbose_name='Heure de fin nuit'),
        ),
        migrations.AlterField(
            model_name='overtimeconfiguration',
            name='night_start_hour',
            field=models.TimeField(blank=True, help_text='Heure de début des heures de nuit (ex: 22:00)', null=True, verbose_name='Heure de début nuit'),
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_type', models.CharField(choices=[('daily', 'Quotidiennes'), ('weekly', 'Hebdomadaires'), ('weekend', 'Weekend'), ('holiday', 'Jours fériés'), ('night', 'Heures de nuit')], help_text="Type d'heures supplémentaires détectées", max_length=20, verbose_name="Type d'heures supplémentaires")),
                ('date', models.DateField(help_text='Date des heures supplémentaires', verbose_name='Date')),
                ('normal_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Nombre d'heures normales travaillées", max_digits=4, verbose_name='Heures normales')),
                ('overtime_hours', models.DecimalField(decimal_places=2, help_text="Nombre d'heures supplémentaires détectées", max_digits=4, verbose_name='Heures supplémentaires')),
                ('total_hours', models.DecimalField(decimal_places=2, help_text='Total des heures travaillées', max_digits=5, verbose_name='Total heures')),
                ('manager_decision', models.CharField(blank=True, choices=[('detected', 'Détectées'), ('pending_approval', 'En attente validation'), ('approved', 'Validées'), ('rejected', 'Rejetées'), ('disputed', 'Contestées')], help_text='Décision du manager', max_length=20, null=True, verbose_name='Décision Manager')),
                ('manager_comment', models.TextField(blank=True, help_text='Commentaire du manager', null=True, verbose_name='Commentaire Manager')),
                ('manager_decision_at', models.DateTimeField(blank=True, help_text='Date de décision du manager', null=True, verbose_name='Décision Manager le')),
                ('rh_decision', models.CharField(blank=True, choices=[('detected', 'Détectées'), ('pending_approval', 'En attente validation'), ('approved', 'Validées'), ('rejected', 'Rejetées'), ('disputed', 'Contestées')], help_text='Décision du RH/DG', max_length=20, null=True, verbose_name='Décision RH')),
                ('rh_comment', models.TextField(blank=True, help_text='Commentaire du RH/DG', null=True, verbose_name='Commentaire RH')),
                ('rh_decision_at', models.DateTimeField(blank=True, help_text='Date de décision du RH/DG', null=True, verbose_name='Décision RH le')),
                ('status', models.CharField(choices=[('detected', 'Détectées'), ('pending_approval', 'En attente validation'), ('approved', 'Validées'), ('rejected', 'Rejetées'), ('disputed', 'Contestées')], default='detected', max_length=20, verbose_name='Statut global')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('attendance_records', models.ManyToManyField(help_text='Pointages ayant généré ces heures supplémentaires', related_name='overtime_records', to='attendance.attendance', verbose_name='Pointages concernés')),
                ('employee', models.ForeignKey(help_text='Employé concerné par les heures supplémentaires', on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
                ('manager', models.ForeignKey(blank=True, help_text='Manager responsable de la validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_overtime_records', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Enregistrement Heures Supplémentaires',
                'verbose_name_plural': 'Enregistrements Heures Supplémentaires',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('employee', 'date', 'overtime_type')},
            },
        ),
        migrations.DeleteModel(
            name='OvertimeRequest',
        ),
    ]
