# Generated by Django 5.2.6 on 2025-10-11 17:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_overtimeconfiguration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mon Entreprise', max_length=200, verbose_name="Nom de l'entreprise")),
                ('work_start_time', models.TimeField(default='08:00', help_text="Heure d'arrivée attendue (ex: 08:00)", verbose_name='Heure de début')),
                ('work_end_time', models.TimeField(default='17:00', help_text='Heure de sortie attendue (ex: 17:00)', verbose_name='Heure de fin')),
                ('late_tolerance_minutes', models.IntegerField(default=15, help_text="Nombre de minutes de tolérance avant qu'un retard soit enregistré", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Tolérance retard (minutes)')),
                ('gps_required', models.BooleanField(default=True, help_text='Si activé, la géolocalisation est obligatoire pour pointer', verbose_name='GPS obligatoire')),
                ('site_center_latitude', models.FloatField(default=6.1304, help_text='Coordonnée GPS latitude du bureau principal (ex: 6.1304 pour Lomé)', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude du bureau')),
                ('site_center_longitude', models.FloatField(default=1.2158, help_text='Coordonnée GPS longitude du bureau principal (ex: 1.2158 pour Lomé)', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude du bureau')),
                ('allowed_radius_meters', models.IntegerField(default=200, help_text='Distance maximale autorisée du bureau pour pointer (ex: 200m)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(5000)], verbose_name='Rayon autorisé (mètres)')),
                ('gps_accuracy_max_meters', models.IntegerField(default=50, help_text='Précision GPS minimale acceptée (ex: 50m)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)], verbose_name='Précision GPS minimale (mètres)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration Entreprise',
                'verbose_name_plural': 'Configuration Entreprise',
            },
        ),
    ]
