# Generated by Django 5.2.6 on 2025-10-15 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_companysettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OvertimeConfiguration',
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='gps_accuracy_max_meters',
            field=models.IntegerField(default=200, help_text='Précision GPS maximale acceptée (ex: 200m)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='Précision GPS maximale (mètres)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='site_center_latitude',
            field=models.FloatField(default=6.140766, help_text='Coordonnée GPS latitude du bureau principal (ex: 6.140766)', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude du bureau'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='site_center_longitude',
            field=models.FloatField(default=1.241907, help_text='Coordonnée GPS longitude du bureau principal (ex: 1.241907)', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude du bureau'),
        ),
        migrations.DeleteModel(
            name='OvertimeRecord',
        ),
    ]
