# Generated by Django 5.2.7 on 2025-10-22 13:06

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_delete_overtimeconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=attendance.models.get_current_date, help_text='Date du pointage', verbose_name='Date'),
        ),
    ]
