# Generated by Django 5.2.7 on 2025-10-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='worked_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Heures travaillées calculées (pause déduite, plafonnées à 8h). NULL si sortie manquante.', max_digits=5, null=True, verbose_name='Heures travaillées'),
        ),
        migrations.AlterField(
            model_name='attendanceanomaly',
            name='anomaly_type',
            field=models.CharField(choices=[('late_arrival', 'Arrivée en retard'), ('early_departure', 'Départ anticipé'), ('missing_punch_out', 'Oubli de sortie'), ('missing_punch_in', "Oubli d'entrée"), ('outside_zone', 'Pointage hors zone'), ('low_accuracy', 'Précision GPS faible'), ('double_punch', 'Double pointage'), ('long_duration', 'Durée de travail excessive')], help_text="Type d'anomalie détectée", max_length=20, verbose_name="Type d'anomalie"),
        ),
    ]
