# Generated by Django 5.2.7 on 2025-10-25 09:28

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_worked_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='accuracy',
            field=models.FloatField(help_text='Précision GPS en mètres', validators=[common.validators.validate_gps_accuracy], verbose_name='Précision GPS'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(help_text='Latitude GPS du pointage', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90), common.validators.validate_gps_coordinate], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(help_text='Longitude GPS du pointage', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180), common.validators.validate_gps_coordinate], verbose_name='Longitude'),
        ),
    ]
