# Generated by Django 5.2.7 on 2025-10-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendance_accuracy_alter_attendance_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceanomaly',
            name='anomaly_type',
            field=models.CharField(choices=[('late_arrival', 'Arrivée en retard'), ('early_departure', 'Départ anticipé'), ('missing_punch_out', 'Oubli de sortie'), ('missing_punch_in', "Oubli d'entrée")], help_text="Type d'anomalie détectée", max_length=20, verbose_name="Type d'anomalie"),
        ),
    ]
