# Generated by Django 5.2.7 on 2025-10-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_technical_anomalies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('web', 'Web')], default='web', help_text='Source du pointage', max_length=10, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('late', 'En retard'), ('early', 'Sortie anticipée')], default='normal', help_text='Statut du pointage (normal, retard, etc.)', max_length=20, verbose_name='Statut'),
        ),
    ]
