# Generated by Django 5.2.7 on 2025-10-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_restore_user_agent_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='late_tolerance_minutes',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='work_end_time',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='work_start_time',
        ),
    ]
