# Generated by Django 5.2.7 on 2025-10-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_purge_anomalies'),
        ('attendance', '0012_remove_unused_company_settings_fields'),
    ]

    operations = [
    ]
