# Generated by Django 5.2.7 on 2025-10-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_delete_attendanceanomaly'),
        ('attendance', '0013_merge_20251030_1012'),
    ]

    operations = [
    ]
